//Home work number 2 by Ivan Kurganski

var numberCellAndColor: [String: Bool] = [:]
//if (key) cell is black value will be true or if (key) cell is white value will be false
numberCellAndColor = ["1A": true,
                      "1B": false,
                      "1C": true,
                      "1D": false,
                      "1E": true,
                      "1F": false,
                      "1G": true,
                      "1H": false,
                      "2A": false,
                      "2B": true,
                      "2C": false,
                      "2D": true,
                      "2E": false,
                      "2F": true,
                      "2G": false,
                      "2H": true,
                      "3A": true,
                      "3B": false,
                      "3C": true,
                      "3D": false,
                      "3E": true,
                      "3F": false,
                      "3G": true,
                      "3H": false,
                      "4A": false,
                      "4B": true,
                      "4C": false,
                      "4D": true,
                      "4E": false,
                      "4F": true,
                      "4G": false,
                      "4H": true,
                      "5A": true,
                      "5B": false,
                      "5C": true,
                      "5D": false,
                      "5E": true,
                      "5F": false,
                      "5G": true,
                      "5H": false,
                      "6A": false,
                      "6B": true,
                      "6C": false,
                      "6D": true,
                      "6E": false,
                      "6F": true,
                      "6G": false,
                      "6H": true,
                      "7A": true,
                      "7B": false,
                      "7C": true,
                      "7D": false,
                      "7E": true,
                      "7F": false,
                      "7G": true,
                      "7H": false,
                      "8A": false,
                      "8B": true,
                      "8C": false,
                      "8D": true,
                      "8E": false,
                      "8F": true,
                      "8G": false,
                      "8H": true]
/* if you want to know what color is cell you should write number of cell on the line below, the answer "true" says that this cell is black and the answer "false" says that this cell is white */
print(numberCellAndColor["1H"] ?? true)

